name: Upload Site and Lambda

on:
  push:
    branches:    
      - staging
      - production

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Cloudformation Template
        uses: ./.github/actions/cloudformation-deploy
        env:
          TEMPLATE: 'template.yml'
          AWS_STACK_NAME: "weather-app-$GITHUB_REF"
          AWS_REGION: 'us-east-1'
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          AWS_DEPLOY_BUCKET: ${{secrets.AWS_DEPLOY_BUCKET}}
      - name: Publish Lambda
        uses: ./.github/actions/lambda-publish
      - name: Upload to S3
        uses: ./.github/actions/s3-upload
